apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argocd-demo-app
  template:
    metadata:
      labels:
        app: argocd-demo-app
    spec:
      containers:
      - name: app
        image: YOUR_IMAGE_REPO_HERE
        ports:
        - containerPort: 80
