name: CI for pokedex-for-ci

on:
  push:
    paths:
      - 'pokedex-for-ci/**'
  pull_request:
    paths:
      - 'pokedex-for-ci/**'

jobs:
  dummy:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Triggered
        run: echo "Changes detected in pokedex-for-ci"
